# Generated by Django 5.2.10 on 2026-01-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attacktimelineevent",
            new_name="core_attack_attack__06d255_idx",
            old_name="core_attac_attack_s_1bc5ee_idx",
        ),
        migrations.RenameIndex(
            model_name="attacktimelineevent",
            new_name="core_attack_event_t_1da647_idx",
            old_name="core_attac_event_ty_b5d6f4_idx",
        ),
        migrations.AlterField(
            model_name="action",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("EXECUTED", "Executed"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="The current status of the action.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attackstate",
            name="current_phase",
            field=models.CharField(
                choices=[
                    ("RECONNAISSANCE", "Reconnaissance"),
                    ("ENUMERATION", "Enumeration"),
                    ("EXPLOITATION", "Exploitation"),
                    ("PRIVILEGE_ESCALATION", "Privilege Escalation"),
                    ("PROOF_OF_COMPROMISE", "Proof of Compromise"),
                    ("COMPLETED", "Completed"),
                ],
                default="RECONNAISSANCE",
                help_text="The current phase of the attack in the kill chain.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="attacktimelineevent",
            name="phase",
            field=models.CharField(
                choices=[
                    ("RECONNAISSANCE", "Reconnaissance"),
                    ("ENUMERATION", "Enumeration"),
                    ("EXPLOITATION", "Exploitation"),
                    ("PRIVILEGE_ESCALATION", "Privilege Escalation"),
                    ("PROOF_OF_COMPROMISE", "Proof of Compromise"),
                    ("COMPLETED", "Completed"),
                ],
                help_text="The kill-chain phase at the time of the event.",
                max_length=50,
            ),
        ),
    ]
