# Generated by Django 5.2.10 on 2026-01-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_rename_core_attac_attack_s_1bc5ee_idx_core_attack_attack__06d255_idx_and_more",
        ),
        ("core", "0002_seed_initial_attack_state"),
    ]

    operations = []
