# Generated by Django 5.2.10 on 2026-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_merge_20260130_1652"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_name",
                    models.CharField(
                        help_text="The registered name of the action to execute (e.g., 'NmapScan').",
                        max_length=255,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validated parameters for the action. To be used with caution by the executor.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        help_text="The current execution status of the task.",
                        max_length=20,
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this task required explicit human approval.",
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True,
                        help_text="Identifier for the user/system that approved this task (for future use).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "output",
                    models.JSONField(
                        blank=True,
                        help_text="Structured output from the completed execution.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if the task failed."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Execution Task",
                "verbose_name_plural": "Execution Tasks",
                "ordering": ["created_at"],
            },
        ),
    ]
