# Generated by Django 5.2.10 on 2026-02-05 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_executiontask"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="reasoning",
            field=models.TextField(
                blank=True, help_text="The AI's reasoning for choosing this action."
            ),
        ),
        migrations.AddField(
            model_name="attackstate",
            name="autonomy_status",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("RUNNING", "Running"),
                    ("PAUSED", "Paused"),
                    ("STOPPED", "Stopped"),
                ],
                default="IDLE",
                help_text="The current operating mode of the autonomous AI.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attackstate",
            name="stop_reason",
            field=models.TextField(
                blank=True,
                help_text="The reason why the autonomy loop stopped (if applicable).",
            ),
        ),
        migrations.AddField(
            model_name="executiontask",
            name="action",
            field=models.ForeignKey(
                blank=True,
                help_text="The high-level action this task implements.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_tasks",
                to="core.action",
            ),
        ),
        migrations.CreateModel(
            name="DefenderAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attack_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defender_alerts",
                        to="core.attackstate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defender Alert",
                "verbose_name_plural": "Defender Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
