# Generated by Django 5.2.10 on 2026-02-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_action_reasoning_attackstate_autonomy_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackerExecutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable identifier for this attacker machine",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the executor daemon"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                        ],
                        default="DISCONNECTED",
                        help_text="Current connection status",
                        max_length=20,
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last received heartbeat",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttackTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable identifier for this target system",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the target system"
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        help_text="OS name/version (e.g., 'Ubuntu 20.04', 'Windows Server 2019')",
                        max_length=100,
                    ),
                ),
                (
                    "vulnerability_profile",
                    models.CharField(
                        blank=True,
                        help_text="Label describing the intended vulnerability set (e.g., 'Metasploitable3')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, this target cannot be selected for autonomy.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
