# Generated by Django 5.2.10 on 2026-02-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_attackerexecutor_attacktarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttackContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                        ],
                        default="READY",
                        help_text="Current operational status of this context.",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("stop_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attacker_executor",
                    models.ForeignKey(
                        help_text="The machine performing the attack.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.attackerexecutor",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        help_text="The authorized target system.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.attacktarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attack Context",
                "verbose_name_plural": "Attack Contexts",
                "ordering": ["-created_at"],
            },
        ),
    ]
