# Generated by Django 5.2.11 on 2026-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_attackcontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="attacktarget",
            name="base_url",
            field=models.URLField(
                blank=True,
                help_text="Base URL for web-based targets (e.g., http://localhost:3000)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="attacktarget",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, help_text="IP address of the target system", null=True
            ),
        ),
    ]
