# Generated by Django 5.2.11 on 2026-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_attacktarget_base_url_alter_attacktarget_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="attackstate",
            name="current_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The current high-level plan generated by the AI, including steps and reasoning.",
            ),
        ),
    ]
