# Generated by Django 5.2.12 on 2026-03-16 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_attackstate_current_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command_template', models.TextField(help_text="Command string with placeholders, e.g. 'curl -I {target}'.")),
            ],
            options={
                'ordering': ['phase', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical phase name (e.g., reconnaissance, discovery).', max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='Target string used for command replacement.', max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=20)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attack_state', models.ForeignKey(help_text='The attack state this result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='core.attackstate')),
                ('command', models.ForeignKey(help_text='The command that was executed.', on_delete=django.db.models.deletion.PROTECT, related_name='results', to='core.command')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='command',
            name='phase',
            field=models.ForeignKey(help_text='Phase this command belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='core.phase'),
        ),
    ]
