# Generated by Django 5.2.12 on 2026-03-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_phases_and_commands'),
        ('core', '0010_command_phase_executionresult_command_phase'),
    ]

    operations = [
    ]
