# Generated by Django 5.2.12 on 2026-05-15 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_attackerexecutor_ssh_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attackstate',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this attack state', on_delete=django.db.models.deletion.CASCADE, related_name='attack_states', to=settings.AUTH_USER_MODEL),
        ),
    ]
