# Generated by Django 5.2.12 on 2026-05-15 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_attackerexecutor_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attackcontext',
            name='owner',
            field=models.ForeignKey(default=1, help_text='The user who owns this context', on_delete=django.db.models.deletion.CASCADE, related_name='attack_contexts', to=settings.AUTH_USER_MODEL),
        ),
    ]
