# core/models.py

from django.db import models
from django.utils import timezone

# According to project_scope.md, the cyber attack lifecycle has several phases.
# These will be used as states in our simulation.
KILL_CHAIN_PHASES = [
    ("RECONNAISSANCE", "Reconnaissance"),
    ("ENUMERATION", "Enumeration"),
    ("EXPLOITATION", "Exploitation"),
    ("PRIVILEGE_ESCALATION", "Privilege Escalation"),
    ("PROOF_OF_COMPROMISE", "Proof of Compromise"),
    ("COMPLETED", "Completed"),
]

from django.db import models

class AttackerExecutor(models.Model):
    """
    Represents a real attacker machine (VM) running the executor daemon.
    Used for heartbeat tracking, availability checks, and autonomy gating.
    """
    class Status(models.TextChoices):
        CONNECTED = 'CONNECTED', 'Connected'
        DISCONNECTED = 'DISCONNECTED', 'Disconnected'

    name = models.CharField(
        max_length=100,
        unique=True,
        help_text="Human-readable identifier for this attacker machine"
    )
    ip_address = models.GenericIPAddressField(
        protocol='both',
        help_text="IP address of the executor daemon"
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DISCONNECTED,
        help_text="Current connection status"
    )
    last_heartbeat = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp of the last received heartbeat"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.ip_address}) [{self.status}]"


class AttackTarget(models.Model):
    """
    Defines an explicit, approved target system for the cyber range.
    Autonomy can only target registered, active targets.
    """
    name = models.CharField(
        max_length=100,
        unique=True,
        help_text="Human-readable identifier for this target system"
    )
    ip_address = models.GenericIPAddressField(
        protocol='both',
        help_text="IP address of the target system",
        null=True,
        blank=True
    )
    base_url = models.URLField(
        max_length=255,
        blank=True,
        help_text="Base URL for web-based targets (e.g., http://localhost:3000)"
    )
    operating_system = models.CharField(
        max_length=100,
        help_text="OS name/version (e.g., 'Ubuntu 20.04', 'Windows Server 2019')"
    )
    vulnerability_profile = models.CharField(
        max_length=100,
        blank=True,
        help_text="Label describing the intended vulnerability set (e.g., 'Metasploitable3')"
    )
    is_active = models.BooleanField(
        default=True,
        help_text="If False, this target cannot be selected for autonomy."
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        status = "Active" if self.is_active else "Inactive"
        target_ref = self.base_url if self.base_url else self.ip_address
        return f"{self.name} ({target_ref}) [{status}]"

AUTONOMY_STATUS_CHOICES = [
    ("IDLE", "Idle"),
    ("RUNNING", "Running"),
    ("PAUSED", "Paused"),
    ("STOPPED", "Stopped"),
]


class AttackState(models.Model):
    """
    Represents the central state of a single attack simulation.

    This model tracks the progress of an attack through the kill chain and
    stores all relevant data discovered or generated during the simulation.
    It acts as the "single source of truth" for a given attack scenario.
    """

    name = models.CharField(
        max_length=255,
        help_text="A unique name for this attack simulation scenario.",
    )

    current_phase = models.CharField(
        max_length=50,
        choices=KILL_CHAIN_PHASES,
        default="RECONNAISSANCE",
        help_text="The current phase of the attack in the kill chain.",
    )

    autonomy_status = models.CharField(
        max_length=20,
        choices=AUTONOMY_STATUS_CHOICES,
        default="IDLE",
        help_text="The current operating mode of the autonomous AI.",
    )

    stop_reason = models.TextField(
        blank=True,
        help_text="The reason why the autonomy loop stopped (if applicable).",
    )

    state_data = models.JSONField(
        default=dict,
        help_text="A JSON object storing dynamic data about the attack state, "
                  "e.g., discovered hosts, vulnerabilities, compromised accounts.",
    )

    current_plan = models.JSONField(
        default=dict,
        blank=True,
        help_text="The current high-level plan generated by the AI, including steps and reasoning.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The timestamp when the simulation was created.",
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="The timestamp of the last state update.",
    )

    class Meta:
        verbose_name = "Attack State"
        verbose_name_plural = "Attack States"
        ordering = ["-updated_at"]

    def __str__(self):
        """
        Returns a string representation of the attack state.
        """
        return f"{self.name} ({self.get_current_phase_display()})"

    def advance_phase(self, new_phase: str):
        """
        Advances the attack to a new phase, if valid.
        """
        phase_names = [phase[0] for phase in KILL_CHAIN_PHASES]
        if new_phase not in phase_names:
            raise ValueError(f"Invalid phase: {new_phase}")

        self.current_phase = new_phase
        self.save(update_fields=["current_phase", "updated_at"])

    def update_state_data(self, new_data: dict):
        """
        Updates the state_data field with new information.
        """
        self.state_data.update(new_data)
        self.save(update_fields=["state_data", "updated_at"])


class Phase(models.Model):
    """Defines a penetration testing phase."""

    name = models.CharField(
        max_length=80,
        unique=True,
        help_text="Canonical phase name (e.g., reconnaissance, discovery).",
    )
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Command(models.Model):
    """Defines an executable command template bound to a phase."""

    phase = models.ForeignKey(
        Phase,
        on_delete=models.PROTECT,
        related_name="commands",
        help_text="Phase this command belongs to.",
    )
    name = models.CharField(max_length=120, unique=True)
    description = models.TextField(blank=True)
    command_template = models.TextField(help_text="Command string with placeholders, e.g. 'curl -I {target}'.")

    class Meta:
        ordering = ["phase", "name"]

    def __str__(self):
        return f"{self.name} ({self.phase.name})"


class ExecutionResult(models.Model):
    """Stores the terminal output from a command execution."""

    command = models.ForeignKey(
        Command,
        on_delete=models.PROTECT,
        related_name="results",
        help_text="The command that was executed.",
    )
    attack_state = models.ForeignKey(
        AttackState,
        on_delete=models.CASCADE,
        related_name="execution_results",
        help_text="The attack state this result belongs to.",
    )
    target = models.CharField(max_length=255, help_text="Target string used for command replacement.")
    status = models.CharField(max_length=20, choices=[("SUCCESS", "Success"), ("FAILED", "Failed")])
    stdout = models.TextField(blank=True)
    stderr = models.TextField(blank=True)
    findings = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Result for {self.command.name} ({self.status})"


ACTION_STATUS_CHOICES = [
    ("PENDING", "Pending"),
    ("EXECUTED", "Executed"),
    ("REJECTED", "Rejected"),
]


class Action(models.Model):
    """
    Represents a single action proposed by the AI agent during an attack.

    Each action is a discrete step in the penetration testing lifecycle,
    like scanning a host or attempting to exploit a vulnerability. Actions
    must be approved by the Policy Engine before they can be executed.
    """

    attack_state = models.ForeignKey(
        AttackState,
        on_delete=models.CASCADE,
        related_name="actions",
        help_text="The attack simulation this action belongs to.",
    )

    name = models.CharField(
        max_length=100,
        help_text="The name of the action to be executed (e.g., 'NmapScan').",
    )

    description = models.TextField(
        blank=True,
        help_text="A brief description of what this action does.",
    )

    reasoning = models.TextField(
        blank=True,
        help_text="The AI's reasoning for choosing this action.",
    )

    parameters = models.JSONField(
        default=dict,
        help_text="The parameters required to execute the action.",
    )

    status = models.CharField(
        max_length=20,
        choices=ACTION_STATUS_CHOICES,
        default="PENDING",
        help_text="The current status of the action.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The timestamp when the action was created.",
    )

    class Meta:
        verbose_name = "Action"
        verbose_name_plural = "Actions"
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.name} on {self.attack_state.name} ({self.status})"


class ActionResult(models.Model):
    """
    Stores the outcome of an executed Action.

    This model provides a detailed record of what happened when an action
    was performed, including whether it succeeded, what data it produced,
    and any relevant log messages.
    """

    action = models.OneToOneField(
        Action,
        on_delete=models.CASCADE,
        related_name="result",
        help_text="The action that produced this result.",
    )

    success = models.BooleanField(
        default=False,
        help_text="Indicates whether the action executed successfully.",
    )

    output = models.JSONField(
        default=dict,
        help_text="Structured data returned by the action (e.g., open ports).",
    )

    log_message = models.TextField(
        blank=True,
        help_text="A human-readable log of the action's outcome.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The timestamp when the result was recorded.",
    )

    class Meta:
        verbose_name = "Action Result"
        verbose_name_plural = "Action Results"
        ordering = ["-created_at"]

    def __str__(self):
        status = "Success" if self.success else "Failure"
        return f"Result for '{self.action.name}' ({status})"


# -----------------------
# Attack Timeline (Phase 1)
# -----------------------

TIMELINE_EVENT_TYPES = [
    ("DECISION", "Decision Proposed"),
    ("POLICY_APPROVED", "Policy Approved"),
    ("POLICY_REJECTED", "Policy Rejected"),
    ("EXECUTION", "Execution"),
    ("STATE_UPDATE", "State Update"),
    ("PHASE_TRANSITION", "Phase Transition"),
]


class AttackTimelineEvent(models.Model):
    """
    Represents a single event in the attack timeline for visualization.

    The timeline is an append-only log of notable events (decisions, policy
    outcomes, execution results, and state/phase changes). It enables the
    dashboard to render a chronological view of the simulated attack without
    requiring complex joins at read time.
    """

    attack_state = models.ForeignKey(
        AttackState,
        on_delete=models.CASCADE,
        related_name="timeline",
        help_text="The attack simulation this timeline event belongs to.",
    )

    # Optional linkage to a specific action (if applicable)
    action = models.ForeignKey(
        Action,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="timeline_events",
        help_text="Related action if this event is tied to a specific action.",
    )

    event_type = models.CharField(
        max_length=32,
        choices=TIMELINE_EVENT_TYPES,
        help_text="The type/category of this timeline event.",
    )

    phase = models.CharField(
        max_length=50,
        choices=KILL_CHAIN_PHASES,
        help_text="The kill-chain phase at the time of the event.",
    )

    message = models.TextField(
        help_text="A concise, human-readable description of the event.",
    )

    data = models.JSONField(
        default=dict,
        help_text="Optional structured data relevant to this event.",
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The timestamp when the event was recorded.",
    )

    class Meta:
        verbose_name = "Attack Timeline Event"
        verbose_name_plural = "Attack Timeline Events"
        ordering = ["created_at"]
        indexes = [
            models.Index(fields=["attack_state", "created_at"]),
            models.Index(fields=["event_type"]),
        ]

    def __str__(self):
        return (
            f"[{self.get_event_type_display()}] "
            f"{self.attack_state.name} @ {self.created_at:%Y-%m-%d %H:%M:%S}"
        )


# -----------------------
# Execution Task Queue (Phase 2 Bridge)
# -----------------------

EXECUTION_TASK_STATUS_CHOICES = [
    ("PENDING", "Pending"),
    ("RUNNING", "Running"),
    ("COMPLETED", "Completed"),
    ("FAILED", "Failed"),
]


class ExecutionTask(models.Model):
    """
    Represents a single, approved action queued for execution.

    This model acts as a durable, auditable bridge between the policy/approval
    layers and the execution layer. It represents the *intent* to execute an
    action, not the execution logic itself. An external executor process will
    poll for PENDING tasks and perform them.

    Safety:
    - This model contains no command strings or direct execution logic.
    - The 'parameters' field must be strictly validated by the executor.
    """

    action_name = models.CharField(
        max_length=255,
        help_text="The registered name of the action to execute (e.g., 'NmapScan').",
    )

    action = models.ForeignKey(
        Action,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="execution_tasks",
        help_text="The high-level action this task implements.",
    )

    parameters = models.JSONField(
        default=dict,
        blank=True,
        help_text="Validated parameters for the action. To be used with caution by the executor.",
    )

    status = models.CharField(
        max_length=20,
        choices=EXECUTION_TASK_STATUS_CHOICES,
        default="PENDING",
        db_index=True,
        help_text="The current execution status of the task.",
    )

    requires_approval = models.BooleanField(
        default=False,
        help_text="Indicates if this task required explicit human approval.",
    )

    approved_by = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="Identifier for the user/system that approved this task (for future use).",
    )

    output = models.JSONField(
        null=True, blank=True, help_text="Structured output from the completed execution."
    )

    error_message = models.TextField(blank=True, help_text="Error details if the task failed.")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Execution Task"
        verbose_name_plural = "Execution Tasks"
        ordering = ["created_at"]

    def __str__(self):
        return f"Task for '{self.action_name}' ({self.status})"


DEFENDER_SEVERITY_CHOICES = [
    ("INFO", "Info"),
    ("LOW", "Low"),
    ("MEDIUM", "Medium"),
    ("HIGH", "High"),
    ("CRITICAL", "Critical"),
]


class DefenderAlert(models.Model):
    """
    Represents a defensive alert triggered by the Defender AI.
    """
    attack_state = models.ForeignKey(
        AttackState, on_delete=models.CASCADE, related_name="defender_alerts"
    )
    severity = models.CharField(max_length=10, choices=DEFENDER_SEVERITY_CHOICES)
    title = models.CharField(max_length=255)
    description = models.TextField()
    recommendation = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Defender Alert"
        verbose_name_plural = "Defender Alerts"
        ordering = ["-created_at"]

    def __str__(self):
        return f"[{self.severity}] {self.title}"


class AttackContext(models.Model):
    """
    Defines the operational context for an autonomous attack.
    Binds a specific attacker executor to a specific target.
    """
    class Status(models.TextChoices):
        READY = 'READY', 'Ready'
        RUNNING = 'RUNNING', 'Running'
        STOPPED = 'STOPPED', 'Stopped'

    attacker_executor = models.ForeignKey(
        AttackerExecutor,
        on_delete=models.PROTECT,
        help_text="The machine performing the attack."
    )
    target = models.ForeignKey(
        AttackTarget,
        on_delete=models.PROTECT,
        help_text="The authorized target system."
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.READY,
        help_text="Current operational status of this context."
    )
    started_at = models.DateTimeField(null=True, blank=True)
    stopped_at = models.DateTimeField(null=True, blank=True)
    stop_reason = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Attack Context"
        verbose_name_plural = "Attack Contexts"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Context: {self.attacker_executor.name} -> {self.target.name} ({self.status})"
