import logging
from core.models import AttackState, Action, AttackTarget

logger = logging.getLogger(__name__)

class DecisionEngine:
    """
    AI Decision Engine responsible for generating attack actions.
    """
    
    def generate_actions(self, attack_state: AttackState) -> list[Action]:
        """
        Generates a list of actions based on the current attack state.
        Includes a fallback mechanism to prevent autonomy stalls.
        """
        proposed_actions = []
        
        # TODO: Integrate LLM/AI planning logic here.
        # For now, we assume the AI returns an empty list if it cannot decide.
        
        # --- FALLBACK LOGIC (TODO CORE-1) ---
        # If no actions were generated by the AI, and we have active targets,
        # generate a fallback reconnaissance action to prevent autonomy stall.
        if not proposed_actions:
            # Check for active targets
            active_targets = AttackTarget.objects.filter(is_active=True)
            
            if active_targets.exists():
                # Select the first active target
                target = active_targets.first()
                
                # Determine target URL (WEB-1 Support)
                # Use base_url if available, otherwise construct from IP
                target_url = target.base_url
                if not target_url and target.ip_address:
                    target_url = f"http://{target.ip_address}"
                
                if target_url:
                    logger.info(f"DecisionEngine: No AI actions. Triggering fallback for {target.name}")
                    
                    fallback_action = Action(
                        attack_state=attack_state,
                        name="HTTPHeaderFetch",
                        description="Fallback initial web reconnaissance to prevent autonomy stall",
                        reasoning="Fallback initial web reconnaissance to prevent autonomy stall",
                        parameters={"target_url": target_url},
                        status="PENDING"
                    )
                    proposed_actions.append(fallback_action)
                    
        return proposed_actions